apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blood-glucose-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blood-glucose-server
    spec:
      imagePullSecrets:
      - name: ccr.ccs.secret
      containers:
      - name: blood-glucose-container
        image: ccr.ccs.tencentyun.com/icx_ai/blood_glucose:2.1
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Gi"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: blood-glucose-service
  name: blood-glucose-service
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: blood-glucose-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "flase"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "10M"
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
  name: blood-glucose-nginx-ingress
  namespace: 
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: blood-glucose-service
          servicePort: 8083
        path: /ai/image/v1.0/bg_img_detect
